version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Starting server in background..."
      - nohup ./gradlew run &
      - sleep 10  # Wait for server to start
      - echo "Testing endpoint..."
      - curl -f http://localhost:7000/ || exit 1
      - echo "Endpoint test passed!"
  post_build:
    commands:
      - pkill -f gradle  # Stop the server
      - echo "Server stopped!"
