version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Starting server in background..."
      - nohup ./gradlew run &
      - echo "Testing endpoint..."
      - wget --tries=5 --retry-connrefused --waitretry=30 http://localhost:7070/
      - echo "Endpoint test passed!"
  post_build:
    commands:
      - pkill -f gradle  # Stop the server
      - echo "Server stopped!"
